### ISSUE TITLE
Damn. The latest merge produced a bug

### ISSUE THREAD

**Issue by jwrobes** [fiery-skippers-2014/QuizzerFly#18]
I'm getting an error on the last merge

**Comment by Answart** [comment]
I'm working on it. Can you explain what type of bug you got?

**Comment by jwrobes** [comment]
Nil class for show all survey erb.

Just log in and register a few times. It may pop up

**Comment by jwrobes** [comment]
The surveys variable didn't get through

And a second time the user class failed.  I think it may have to do with
sessions.
